### ISSUE TITLE
Any chance for multiple correct answers?

### ISSUE THREAD

**Issue by wolffe** [yusufsefasezer/ysQuiz.js#1]
Any chance for multiple correct answers?

So, checkboxes instead of radio boxes?

Ideally, I see this library providing both single-answer questions AND multiple-answer questions.

**Comment by yusufsefasezer** [comment]
Hello,

Yes, we can add multiple correct answer feature. However, needs time to change the structure. 

Thank you for your recommendation.

**Comment by yusufsefasezer** [comment]
Hello, completed.
